---
  extends: "eslint:recommended"
  rules:
    jsx-quotes: 1
    react/display-name: 1
    react/jsx-boolean-value: 1
    react/jsx-curly-spacing: 1
    react/jsx-no-duplicate-props: 1
    react/jsx-no-undef: 1
    react/jsx-uses-react: 1
    react/jsx-uses-vars: 1
    react/no-danger: 1
    react/no-did-mount-set-state: 1
    react/no-did-update-set-state: 1
    react/no-unknown-property: 1
    react/prop-types: 1
    react/react-in-jsx-scope: 1
    react/require-extension: 1
    react/self-closing-comp: 1
    react/sort-prop-types: 1
    react/wrap-multilines: 1
  env:
    browser: true
    commonjs: true
    jquery: true
  parserOptions:
    ecmaFeatures:
      jsx: true
  plugins:
    - "react"
