---
  settings:
    react:
      version: "detect"
  extends: ["eslint:recommended", "plugin:react/recommended"]
  rules:
    jsx-quotes: 1
  env:
    browser: true
    commonjs: true
    jquery: true
    es6: true
  parserOptions:
    sourceType: "module"
    ecmaVersion: 6
    ecmaFeatures:
      jsx: true
      arrowFunctions: true
  plugins:
    - "react"
